### LOGIN USER
POST http://localhost:5000/api/auth
Content-Type: application/json

{
  "email": "fred@bedrock.com",
  "password": "123456"
}

### AUTH USER
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjIwOTFlZGJmNWVjY2Y4ZDkwMjg2MzVjIn0sImlhdCI6MTY0NDg0MzM2MywiZXhwIjoxNjQ1MjAzMzYzfQ.BBVXtOcBdaAJin68VlpVpBX3iHUTiMZMA3UJ8XAdTmg

